apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: anjo
  name: anjo
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources: ["deployments", "replicasets", "pods", "services", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
