stages:
  - sync
  - version
syncing:
  stage: sync
  image: shirzadi/md2conf
  script: |
      for file in $(git show $CI_COMMIT_SHA --name-status | grep "^[AM]\s.*md" | awk '{print $2}'); do
        echo "> Sync $file";
        mark -u $CONFLUENCE_USER -p $CONFLUENCE_PASSWORD -b $CONFLUENCE_URL -f $file || exit 1;
        echo;
      done
version:
  stage: version
  image: amirfatemi/gitlab-version:latest
  script:
    - release changelog
    - release commit-and-tag CHANGELOG.md
