stages:
  - sync
test:
  stage: sync
  image: shirzadi/md2conf
  script: |
      git show $CI_COMMIT_SHA --name-status > output
#      for file in $(find -type f -name '*.md'); do
#        echo "> Sync $file";
#        mark -u $CONFLUENCE_USER -p $CONFLUENCE_PASSWORD -b $CONFLUENCE_URL -f $file || exit 1;
#        echo;
#      done
