apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cdn
  name: cdn
rules:
#- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["deployments", "replicasets", "pods", "services", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdn
  namespace: cdn
subjects:
- kind: User
  name: cdn
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cdn
  apiGroup: rbac.authorization.k8s.io