version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDISINSIGHT_REDIS_HOSTS=redis:6379
    depends_on:
      - redis
  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis
